spring.application.name=nttuc1

# To always run the docker services 
spring.docker.compose.lifecycle-management=start-and-stop

# Base URL where Ollama is running locally
#spring.ai.ollama.init.pull-model-strategy=when-missing
#spring.ai.ollama.init.chat.model=llama3.1
spring.ai.ollama.init.embedding.model=mistral
spring.ai.ollama.base-url=http://localhost:11434

# The specific local model
#spring.ai.ollama.chat.options.model=llama3.1
