spring.application.name=nttuc1

spring.ai.openai.api-key=sk-proj-XCynv_zVGUZmfu1haZeW8Wt409x6wnNt2lHbNteHbVRavSs8AkyPVdYVLQ-pMhDyVJMXxx9BLxT3BlbkFJ24w9wCw8KnEdyuQGM5meHnGU40g2_yqTzh3aYSc_nKDYtm46Re7cKiSPFtmgY-HwPI_tkBA8wAsp


